### PR TITLE
Fixes #2205 create without geometry by removing geometries that are b…

### PR DESCRIPTION
**Pull request by ryangroth5**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This will suppress data going to reachCreate that does not have a valid geometry or length enabling reaches to be created without geometries.

* **What is the current behavior?** (You can also link to an open issue here)
invalid data goes to reach create 

- **What is the new behavior (if this is a feature change)?**
invalid data is filtered from going to reach create

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

- **Other information**:
logged a bug about not being able to remove geometries after they are created as low priority.

### CODE REVIEW

**Review by ngottlieb — COMMENTED** [review]
do you mind if I re-do this differently? I'd prefer to fix it upstream and think the changes will be simpler and more maintainable.

**Comment by ryangroth5** [comment]
I updated this to account for the new verify/unverify PR that was merged.

**Comment by ryangroth5** [comment]
@ngottlieb saw your comment, no, don't mind at all.

**Comment by ryangroth5** [comment]
ticket link: https://github.com/AmericanWhitewater/wh2o/issues/2222

**Comment by ryangroth5** [comment]
@ngottlieb this also tweaks error detail reporting on reach create failure which might be worth salvaging in some way

**Comment by ngottlieb** [comment]
Note: this was supposed to work towards https://github.com/AmericanWhitewater/wh2o/issues/2228.

It's been replaced by https://github.com/AmericanWhitewater/wh2o-vue/pull/351

**Pull request closed without merging**
